# Generated by Django 5.0.3 on 2024-06-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionpopularity',
            name='view_count',
            field=models.IntegerField(default=91),
        ),
    ]
