# Generated by Django 5.0.3 on 2024-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='huffman_data',
            field=models.BinaryField(default=b'0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='content',
            field=models.TextField(),
        ),
    ]
