# Generated by Django 5.0.6 on 2024-06-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_diaryentry_total_rating_diaryrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='total_rating',
            new_name='rating',
        ),
    ]
